import { createRequire } from "node:module";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import { icons } from "@phosphor-icons/core";
import { format } from "prettier";

import { pathsFromTrustedPhosphorSvg } from "../src/canvas/phosphor-svg-compiler";

const require = createRequire(import.meta.url);
const packageEntry = require.resolve("@phosphor-icons/core");
const packageRoot = path.resolve(path.dirname(packageEntry), "..");
const outputDirectory = path.resolve("public/phosphor-icons");
const outputPath = path.join(outputDirectory, "catalog-v2.1.1.json");
const namesOutputPath = path.resolve("src/canvas/phosphor-icon-names.ts");

function labelFor(name: string) {
  return name
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}

const catalog = await Promise.all(
  icons.map(async (icon) => {
    const svgPath = path.join(
      packageRoot,
      "assets",
      "fill",
      `${icon.name}-fill.svg`,
    );
    const svg = await readFile(svgPath, "utf8");
    return {
      name: icon.name,
      label: labelFor(icon.name),
      categories: [...icon.categories],
      tags: icon.tags.filter((tag) => !tag.startsWith("*")),
      paths: pathsFromTrustedPhosphorSvg(svg, icon.name),
    };
  }),
);

await mkdir(outputDirectory, { recursive: true });
await writeFile(
  outputPath,
  `${JSON.stringify({ version: "2.1.1", viewBox: 256, icons: catalog })}\n`,
);
await writeFile(
  namesOutputPath,
  await format(
    `// Generated by pnpm icons:generate. Do not edit by hand.\nexport const phosphorIconNames = new Set(${JSON.stringify(catalog.map((icon) => icon.name))});\n`,
    { parser: "typescript" },
  ),
);

process.stdout.write(
  `Generated ${catalog.length} icons at ${outputPath} and ${namesOutputPath}\n`,
);
